spring.application.name=microservice-authentification
server.port=8085

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

spring.cloud.config.uri=http://localhost:9101

eureka.client.service-url.defaultZone=http://localhost:9102/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true